#pragma once

//Klase za izraze
#include "Primarni_izraz.h"
#include "Postfiks_izraz.h"
#include "Lista_argumenata.h"
#include "Unarni_izraz.h"
#include "Unarni_operator.h"
#include "Cast_izraz.h"
#include "Ime_tipa.h"
#include "Specifikator_tipa.h"
#include "Multiplikativni_izraz.h"
#include "Aditivni_izraz.h"
#include "Odnosni_izraz.h"
#include "Jednakosni_izraz.h"
#include "Bin_i_izraz.h"
#include "Bin_xili_izraz.h"
#include "Bin_ili_izraz.h"
#include "Log_i_izraz.h"
#include "Log_ili_izraz.h"
#include "Izraz_pridruzivanja.h"
#include "Izraz.h"

//Klase za naredbenu strukturu programa
#include "Slozena_naredba.h"
#include "Lista_naredbi.h"
#include "Naredba.h"
#include "Izraz_naredba.h"
#include "Naredba_grananja.h"
#include "Naredba_petlje.h"
#include "Naredba_skoka.h"
#include "Prijevodna_jedinica.h"
#include "Vanjska_deklaracija.h"

//Klase za deklaracije i definicije
#include "Definicija_funkcije.h"
#include "Lista_parametara.h"
#include "Deklaracija_parametra.h"
#include "Lista_deklaracija.h"
#include "Deklaracija.h"
#include "Lista_init_deklaratora.h"
#include "Init_deklarator.h"
#include "Izravni_deklarator.h"
#include "Inicijalizator.h"
#include "Lista_izraza_pridruzivanja.h"
